### ISSUE TITLE
custom actions - created actions not triggerable

### ISSUE THREAD

**Issue by pasnox** [tibirna/qgit#18] opened 2018-04-19 20:57 UTC
When i create actions without giving them mnemonic key (ie &pull), then clicking the menu action trigger an issue telling the action name was not found.
I had to press Alt key while menu is popped to see the mnemonic in the actions text and rename all my custom actions to place the mnemonic so that everything match and works.

Linux, KDE, Breeze

**Comment by tibirna** [comment] 2018-04-20 11:53
This should be fixed with https://github.com/tibirna/qgit/commit/7b8f1ff9c . It's not yet in a release, though.

Thanks.

**Comment by kkofler** [comment] 2019-08-23 12:08
This is a duplicate of #12. The commit that fixes it is in the QGit 2.8 release. This bug can be closed now.

**Closed** 2019-08-24 19:26 UTC
